builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - openbsd
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
      - ppc64
    ignore:
      - goos: windows
        goarch: arm
